baseURL = 'https://blog.fenv.net/'
languageCode = 'zh-CN'
title = '学记'
theme = 'fenv'
buildDrafts = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4